### ISSUE TITLE
Claiming a church fails

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/AccessApi#83]
Looks like permissions issue. `/people/:id` and `/people/recent` throws 401.

**Comment by jzongker** [comment]
Can you clarify two things?

1. By "claim a church" are you talking about claiming the MembershipApi.person and AccessApi.user records at an existing church based on your email address or are you talking about creating a new church?
2. Those two api calls shouldn't be called at all in the shared AppBase code that handles either of those processes.  Is it Chums throwing this error?  If so I think I just need an access denied message there.  Just because you have a user/person record at a church doesn't mean you have permissions to use chums.

**Comment by pranavmalvawala** [comment]
Okay, so by "claiming", I mean the process of claiming the church. The way we can be part of any church just by selecting the church in the popup at login.

1. There is no problem here, apis work just fine, so a user church record, create a user in membership api, all of that works.
2. Yes, its the chums. 

Sorry I should have been more clear. Technically the problem is not with claiming church at all, its what happens after. After you log into chums you know the app would be redirected to /people routes and it is here, the apps crashes. The problem is `/people/:id` and `/people/recent` throwing 401 which I think should work cause I just claimed the church. or is it not the case?

**Comment by jzongker** [comment]
That is proper behavior, it just needs to fail more gracefully.

When you search for and select a church from the popup, you're not claiming ownership of the entire church.  You are only claiming the person record at that church whose email matches the email on your user record.  If that person record doesn't exist, it creates one (a visitor) and claims it.

That's it though.  You have no special access to this church at this point, you're just a visitor.  With StreamingLive and B1 visitors are fully welcome to use the app (at least parts of it), however Chums is only for church administrators to use, not visitors.  We just need a message that shows up in Chums stating that you don't have access instead of crashing.

**Comment by pranavmalvawala** [comment]
That makes sense, I'll take it from here. 

Just a quick thought on the approach, we've got a successCallback hook on LoginPage component right? I'll just check for `people/view` permission, if they don't have it show them the error. If you've got any better approach then let me know.
